"use client";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { socket } from "@/lib/socket";
import { useEffect, useState } from "react";
import { useClientGameStore } from "@/lib/store/clientStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setSocketId = useClientGameStore((state) => state.setSocketId);
  const socketId = useClientGameStore((state) => state.socketId);

  useEffect(() => {
    // if (playerClient.current == null) {
    //   getPlayerClient().initialize();
    // }

    function onConnect() {
      setSocketId(socket.id!);
    }
    if (socket.connected) {
      onConnect();
    }
    socket.on("connect", onConnect);

    return () => {
      socket.off("connect", onConnect);
    };
  }, []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
